apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: image-cloner
webhooks:
  - name: image-cloner.default.svc.cluster.local
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps",  ""]
        apiVersions: ["v1"]
        resources: ["deployment", "daemonset", "pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "default"
        name: "image-cloner"
        path: "/clone-image"
      caBundle: "${CA_PEM_B64}"

