apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-cloner
  name: image-cloner
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: image-cloner

